### ISSUE TITLE
merged GFF3 file coverage

### ISSUE THREAD

**Issue by wyim-pgl** [PrecociousLlama/TE_stats#1]
Dear thkhavi,

Thank you for the nice script for REPET.

I just wonder, is there any merged GFF3 file coverage script?

In draft genome we have a thousand scaffold and it's hard to merge it all together.

Do you have any script for that?

When I run it with merged gff3 file, it generated key error.

Populating genomic array of sets.
Traceback (most recent call last):
  File "classification_te_coverage.py", line 155, in <module>
    GAS[t_element.iv] += "TE@" + (t_element.attr['Target'])[:3]
  File "_HTSeq.pyx", line 526, in HTSeq._HTSeq.GenomicArray.__getitem__ (src/_HTSeq.c:10785)
KeyError: 'Scaffold_1'

Thank you.

Won

**Comment by thkhavi** [comment]
Hi Won,

At this time the script is only able to handle individual contig GFF3 files and not merged GFF3 files. It should be relatively easy to modify the python script to be able to handle a merged GFF3, but I don't have an implementation for it currently.

Thanks,
Sandra

**Comment by wyim-pgl** [comment]
Sandra,

I have no idea to handle the python.

I will find another way.

Again, thank you anyway.
